spring.application.name=ecom

# DB Settings
spring.datasource.url=jdbc:mysql://localhost:3306/ecom_june_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=deepcoder

#hibernate Settings
spring.jpa.hibernate.ddl-auto=update