spring.application.name=GatewayService

server.port=1111

# Eureka Client Setup
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

# Gateway Config
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Routing Config
# configure 3 props: id, uri, predicate[0]=path 
# Route 1: Routes[0] : Seller Service 
# id
spring.cloud.gateway.routes[0].id=seller-service
# uri of the seller-service
spring.cloud.gateway.routes[0].uri=lb://seller-service
# path predicate
spring.cloud.gateway.routes[0].predicates[0]=Path=/seller-service/**


# Route 2: Routes[1] : Auth Service 
# id
spring.cloud.gateway.routes[1].id=auth-service
# uri of the seller-service
spring.cloud.gateway.routes[1].uri=lb://auth-service
# path predicate
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth-service/**

